# Parametrize the transformations

#[generate.mesh]
# include_doors = false
# format = "stl"

[generate.gazebo]
ros_version = "ros2"
ros_pkg = "gazebo_simulation"

[generate.occ_grid]
# generation parameters
laser_height = 0.289 # Adjust based on laser height of robot
border = 50
# map_server required metadata
resolution = 0.05
occupied_threshold = 0.65
free_threshold = 0.196
negate = 0
unknown_value = 200
occupied_value = 0
free_value = 255

#[generate.tts]
#robot_translation_x = -0.7
#robot_translation_z = 1.0
